site_name: bcore
site_url: https://github.com/Byron/bcore
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/bcore

docs_dir: ../../src/md
site_dir: ../../doc/mkdocs/html

pages:
- ['index.md', 'Home']
- ['bsemantic.md', 'Packages', 'bSemantic']
- ['license.md', 'About', 'License']

copyright: Copyright &copy; 2014, <a href="https://www.linkedin.com/in/sebastianthiel">Sebastian Thiel & Contributors</a>.
