# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bdevel/core/processing/tractor/submission/gui/ui/chunk.ui'
#
# Created: Mon Aug  5 14:46:20 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FrameSequenceBox(object):
    def setupUi(self, FrameSequenceBox):
        FrameSequenceBox.setObjectName("FrameSequenceBox")
        FrameSequenceBox.resize(560, 102)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FrameSequenceBox.sizePolicy().hasHeightForWidth())
        FrameSequenceBox.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(FrameSequenceBox)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.range = QtGui.QHBoxLayout()
        self.range.setObjectName("range")
        self.first_label = QtGui.QLabel(FrameSequenceBox)
        self.first_label.setObjectName("first_label")
        self.range.addWidget(self.first_label)
        self.first = QtGui.QDoubleSpinBox(FrameSequenceBox)
        self.first.setDecimals(0)
        self.first.setMaximum(9999.0)
        self.first.setObjectName("first")
        self.range.addWidget(self.first)
        self.last_label = QtGui.QLabel(FrameSequenceBox)
        self.last_label.setObjectName("last_label")
        self.range.addWidget(self.last_label)
        self.last = QtGui.QDoubleSpinBox(FrameSequenceBox)
        self.last.setDecimals(0)
        self.last.setMaximum(9999.0)
        self.last.setObjectName("last")
        self.range.addWidget(self.last)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.range.addItem(spacerItem)
        self.step_label = QtGui.QLabel(FrameSequenceBox)
        self.step_label.setObjectName("step_label")
        self.range.addWidget(self.step_label)
        self.step_size = QtGui.QDoubleSpinBox(FrameSequenceBox)
        self.step_size.setDecimals(0)
        self.step_size.setObjectName("step_size")
        self.range.addWidget(self.step_size)
        self.verticalLayout.addLayout(self.range)
        self.options = QtGui.QHBoxLayout()
        self.options.setObjectName("options")
        self.label = QtGui.QLabel(FrameSequenceBox)
        self.label.setObjectName("label")
        self.options.addWidget(self.label)
        self.chunk_size = QtGui.QDoubleSpinBox(FrameSequenceBox)
        self.chunk_size.setDecimals(0)
        self.chunk_size.setMinimum(-999.0)
        self.chunk_size.setMaximum(999.0)
        self.chunk_size.setObjectName("chunk_size")
        self.options.addWidget(self.chunk_size)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.options.addItem(spacerItem1)
        self.source_label = QtGui.QLabel(FrameSequenceBox)
        self.source_label.setObjectName("source_label")
        self.options.addWidget(self.source_label)
        self.source = QtGui.QComboBox(FrameSequenceBox)
        self.source.setObjectName("source")
        self.options.addWidget(self.source)
        self.order_label = QtGui.QLabel(FrameSequenceBox)
        self.order_label.setObjectName("order_label")
        self.options.addWidget(self.order_label)
        self.order = QtGui.QComboBox(FrameSequenceBox)
        self.order.setObjectName("order")
        self.options.addWidget(self.order)
        self.verticalLayout.addLayout(self.options)

        self.retranslateUi(FrameSequenceBox)
        QtCore.QMetaObject.connectSlotsByName(FrameSequenceBox)

    def retranslateUi(self, FrameSequenceBox):
        FrameSequenceBox.setWindowTitle(QtGui.QApplication.translate("FrameSequenceBox", "Chunk", None, QtGui.QApplication.UnicodeUTF8))
        FrameSequenceBox.setTitle(QtGui.QApplication.translate("FrameSequenceBox", "Frame Range and Chunking", None, QtGui.QApplication.UnicodeUTF8))
        self.first_label.setText(QtGui.QApplication.translate("FrameSequenceBox", "First ", None, QtGui.QApplication.UnicodeUTF8))
        self.first.setToolTip(QtGui.QApplication.translate("FrameSequenceBox", "First frame to operate on", None, QtGui.QApplication.UnicodeUTF8))
        self.last_label.setText(QtGui.QApplication.translate("FrameSequenceBox", "Last", None, QtGui.QApplication.UnicodeUTF8))
        self.last.setToolTip(QtGui.QApplication.translate("FrameSequenceBox", "last frame to operate on", None, QtGui.QApplication.UnicodeUTF8))
        self.step_label.setText(QtGui.QApplication.translate("FrameSequenceBox", "By ", None, QtGui.QApplication.UnicodeUTF8))
        self.step_size.setToolTip(QtGui.QApplication.translate("FrameSequenceBox", "The frame-difference between two rendered frames", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FrameSequenceBox", "Chunk Size", None, QtGui.QApplication.UnicodeUTF8))
        self.chunk_size.setToolTip(QtGui.QApplication.translate("FrameSequenceBox", "Amount of frames per task on the farm. Smaller chunks means more tasks to work on. 0 makes one chunk. Negative values create that many chunks", None, QtGui.QApplication.UnicodeUTF8))
        self.source_label.setText(QtGui.QApplication.translate("FrameSequenceBox", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.source.setToolTip(QtGui.QApplication.translate("FrameSequenceBox", "The source for the first and last frame", None, QtGui.QApplication.UnicodeUTF8))
        self.order_label.setToolTip(QtGui.QApplication.translate("FrameSequenceBox", "Determines how chunks are ordered. Useful to make sure you see certain frames first", None, QtGui.QApplication.UnicodeUTF8))
        self.order_label.setText(QtGui.QApplication.translate("FrameSequenceBox", "Order", None, QtGui.QApplication.UnicodeUTF8))
        self.order.setToolTip(QtGui.QApplication.translate("FrameSequenceBox", "The order in which chunks will be created. Useful to get certain frames before others", None, QtGui.QApplication.UnicodeUTF8))

