# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bdevel/core/processing/tractor/submission/gui/ui/job.ui'
#
# Created: Tue Jul 30 18:01:05 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_JobGeneratorBox(object):
    def setupUi(self, JobGeneratorBox):
        JobGeneratorBox.setObjectName("JobGeneratorBox")
        JobGeneratorBox.resize(455, 367)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(JobGeneratorBox.sizePolicy().hasHeightForWidth())
        JobGeneratorBox.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(JobGeneratorBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_layout = QtGui.QHBoxLayout()
        self.title_layout.setObjectName("title_layout")
        self.title_label = QtGui.QLabel(JobGeneratorBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setMinimumSize(QtCore.QSize(50, 0))
        self.title_label.setObjectName("title_label")
        self.title_layout.addWidget(self.title_label)
        self.title = QtGui.QLineEdit(JobGeneratorBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setObjectName("title")
        self.title_layout.addWidget(self.title)
        self.verticalLayout.addLayout(self.title_layout)
        self.file_layout = QtGui.QHBoxLayout()
        self.file_layout.setObjectName("file_layout")
        self.file_label = QtGui.QLabel(JobGeneratorBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_label.sizePolicy().hasHeightForWidth())
        self.file_label.setSizePolicy(sizePolicy)
        self.file_label.setMinimumSize(QtCore.QSize(50, 0))
        self.file_label.setObjectName("file_label")
        self.file_layout.addWidget(self.file_label)
        self.file = QtGui.QLineEdit(JobGeneratorBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file.sizePolicy().hasHeightForWidth())
        self.file.setSizePolicy(sizePolicy)
        self.file.setObjectName("file")
        self.file_layout.addWidget(self.file)
        self.verticalLayout.addLayout(self.file_layout)
        self.advanced_layout = QtGui.QHBoxLayout()
        self.advanced_layout.setObjectName("advanced_layout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.advanced_layout.addItem(spacerItem)
        self.advanced = QtGui.QCheckBox(JobGeneratorBox)
        self.advanced.setObjectName("advanced")
        self.advanced_layout.addWidget(self.advanced)
        self.verticalLayout.addLayout(self.advanced_layout)
        self.advanced_widget = QtGui.QWidget(JobGeneratorBox)
        self.advanced_widget.setObjectName("advanced_widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.advanced_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.service_layout = QtGui.QHBoxLayout()
        self.service_layout.setObjectName("service_layout")
        self.label = QtGui.QLabel(self.advanced_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.service_layout.addWidget(self.label)
        self.service = QtGui.QLineEdit(self.advanced_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.service.sizePolicy().hasHeightForWidth())
        self.service.setSizePolicy(sizePolicy)
        self.service.setObjectName("service")
        self.service_layout.addWidget(self.service)
        self.verticalLayout_3.addLayout(self.service_layout)
        self.comment = QtGui.QTextEdit(self.advanced_widget)
        self.comment.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment.sizePolicy().hasHeightForWidth())
        self.comment.setSizePolicy(sizePolicy)
        self.comment.setMaximumSize(QtCore.QSize(16777215, 80))
        self.comment.setObjectName("comment")
        self.verticalLayout_3.addWidget(self.comment)
        self.verticalLayout.addWidget(self.advanced_widget)

        self.retranslateUi(JobGeneratorBox)
        QtCore.QObject.connect(self.advanced, QtCore.SIGNAL("clicked(bool)"), self.advanced_widget.setVisible)
        QtCore.QMetaObject.connectSlotsByName(JobGeneratorBox)

    def retranslateUi(self, JobGeneratorBox):
        JobGeneratorBox.setWindowTitle(QtGui.QApplication.translate("JobGeneratorBox", "Job", None, QtGui.QApplication.UnicodeUTF8))
        JobGeneratorBox.setTitle(QtGui.QApplication.translate("JobGeneratorBox", "Job Information", None, QtGui.QApplication.UnicodeUTF8))
        self.title_label.setText(QtGui.QApplication.translate("JobGeneratorBox", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setToolTip(QtGui.QApplication.translate("JobGeneratorBox", "The jobs title, most prominent means of identification", None, QtGui.QApplication.UnicodeUTF8))
        self.file_label.setText(QtGui.QApplication.translate("JobGeneratorBox", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.file.setToolTip(QtGui.QApplication.translate("JobGeneratorBox", "The source file the job is supposed to deal with", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced.setToolTip(QtGui.QApplication.translate("JobGeneratorBox", "If enabled, a comment field will be shown", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced.setText(QtGui.QApplication.translate("JobGeneratorBox", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("JobGeneratorBox", "Service Expr.", None, QtGui.QApplication.UnicodeUTF8))
        self.service.setToolTip(QtGui.QApplication.translate("JobGeneratorBox", "A tractor service expression, see http://renderman.pixar.com/resources/current/tractor/scripting.html#remote-servers-launch-expressions-and-runtime-substitution", None, QtGui.QApplication.UnicodeUTF8))
        self.comment.setToolTip(QtGui.QApplication.translate("JobGeneratorBox", "A comment to be displayed with your job", None, QtGui.QApplication.UnicodeUTF8))

